#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::XamarinViewPager.Resource.Array.Xamarin_effects = global::Sample.Resource.Array.Xamarin_effects;
			global::XamarinViewPager.Resource.Attribute.fadeEnabled = global::Sample.Resource.Attribute.fadeEnabled;
			global::XamarinViewPager.Resource.Attribute.outlineColor = global::Sample.Resource.Attribute.outlineColor;
			global::XamarinViewPager.Resource.Attribute.outlineEnabled = global::Sample.Resource.Attribute.outlineEnabled;
			global::XamarinViewPager.Resource.Attribute.style = global::Sample.Resource.Attribute.style;
			global::XamarinViewPager.Resource.Id.accordion = global::Sample.Resource.Id.accordion;
			global::XamarinViewPager.Resource.Id.cubein = global::Sample.Resource.Id.cubein;
			global::XamarinViewPager.Resource.Id.cubeout = global::Sample.Resource.Id.cubeout;
			global::XamarinViewPager.Resource.Id.fliphorizontal = global::Sample.Resource.Id.fliphorizontal;
			global::XamarinViewPager.Resource.Id.flipvertical = global::Sample.Resource.Id.flipvertical;
			global::XamarinViewPager.Resource.Id.rotatedown = global::Sample.Resource.Id.rotatedown;
			global::XamarinViewPager.Resource.Id.rotateup = global::Sample.Resource.Id.rotateup;
			global::XamarinViewPager.Resource.Id.stack = global::Sample.Resource.Id.stack;
			global::XamarinViewPager.Resource.Id.standard = global::Sample.Resource.Id.standard;
			global::XamarinViewPager.Resource.Id.tablet = global::Sample.Resource.Id.tablet;
			global::XamarinViewPager.Resource.Id.zoomin = global::Sample.Resource.Id.zoomin;
			global::XamarinViewPager.Resource.Id.zoomout = global::Sample.Resource.Id.zoomout;
			global::XamarinViewPager.Resource.String.ApplicationName = global::Sample.Resource.String.ApplicationName;
			global::XamarinViewPager.Resource.Styleable.XamarinViewPager = global::Sample.Resource.Styleable.XamarinViewPager;
			global::XamarinViewPager.Resource.Styleable.XamarinViewPager_fadeEnabled = global::Sample.Resource.Styleable.XamarinViewPager_fadeEnabled;
			global::XamarinViewPager.Resource.Styleable.XamarinViewPager_outlineColor = global::Sample.Resource.Styleable.XamarinViewPager_outlineColor;
			global::XamarinViewPager.Resource.Styleable.XamarinViewPager_outlineEnabled = global::Sample.Resource.Styleable.XamarinViewPager_outlineEnabled;
			global::XamarinViewPager.Resource.Styleable.XamarinViewPager_style = global::Sample.Resource.Styleable.XamarinViewPager_style;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int Xamarin_effects = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int fadeEnabled = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int outlineColor = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int outlineEnabled = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int style = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000b
			public const int accordion = 2130968587;
			
			// aapt resource value: 0x7f040002
			public const int cubein = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int cubeout = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int fliphorizontal = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int flipvertical = 2130968580;
			
			// aapt resource value: 0x7f04000c
			public const int jazzy_pager = 2130968588;
			
			// aapt resource value: 0x7f040018
			public const int menu_accordian = 2130968600;
			
			// aapt resource value: 0x7f04000f
			public const int menu_cube_in = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int menu_cube_out = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int menu_flip_horizontal = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int menu_flip_vertical = 2130968593;
			
			// aapt resource value: 0x7f040017
			public const int menu_rotate_down = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int menu_rotate_up = 2130968598;
			
			// aapt resource value: 0x7f040013
			public const int menu_stack = 2130968595;
			
			// aapt resource value: 0x7f04000d
			public const int menu_standard = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int menu_tablet = 2130968590;
			
			// aapt resource value: 0x7f040014
			public const int menu_zoom_in = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int menu_zoom_out = 2130968597;
			
			// aapt resource value: 0x7f04000a
			public const int rotatedown = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int rotateup = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int stack = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int standard = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int tablet = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int zoomin = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int zoomout = 2130968584;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] XamarinViewPager = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int XamarinViewPager_fadeEnabled = 1;
			
			// aapt resource value: 3
			public const int XamarinViewPager_outlineColor = 3;
			
			// aapt resource value: 2
			public const int XamarinViewPager_outlineEnabled = 2;
			
			// aapt resource value: 0
			public const int XamarinViewPager_style = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
