#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinViewPager.Resource", IsApplication=false)]

namespace XamarinViewPager
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public static int Xamarin_effects = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int fadeEnabled = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int outlineColor = 2130771971;
			
			// aapt resource value: 0x7f010002
			public static int outlineEnabled = 2130771970;
			
			// aapt resource value: 0x7f010000
			public static int style = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f02000b
			public static int accordion = 2130837515;
			
			// aapt resource value: 0x7f020002
			public static int cubein = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int cubeout = 2130837507;
			
			// aapt resource value: 0x7f020005
			public static int fliphorizontal = 2130837509;
			
			// aapt resource value: 0x7f020004
			public static int flipvertical = 2130837508;
			
			// aapt resource value: 0x7f02000a
			public static int rotatedown = 2130837514;
			
			// aapt resource value: 0x7f020009
			public static int rotateup = 2130837513;
			
			// aapt resource value: 0x7f020006
			public static int stack = 2130837510;
			
			// aapt resource value: 0x7f020000
			public static int standard = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int tablet = 2130837505;
			
			// aapt resource value: 0x7f020007
			public static int zoomin = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int zoomout = 2130837512;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public static int ApplicationName = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] XamarinViewPager = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public static int XamarinViewPager_fadeEnabled = 1;
			
			// aapt resource value: 3
			public static int XamarinViewPager_outlineColor = 3;
			
			// aapt resource value: 2
			public static int XamarinViewPager_outlineEnabled = 2;
			
			// aapt resource value: 0
			public static int XamarinViewPager_style = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
